#settings = {
#        'bootstrap.servers': 'localhost:9092',
#        'group.id': 'mygroup',
#        'client.id': 'client-1',
#        'enable.auto.commit': True,
#        'session.timeout.ms': 6000,
#        'default.topic.config': {'auto.offset.reset': 'smallest'}
#}

kafka:
  bootstrap.servers: 'localhost:9092'
  group.id: 'mygroup'
  client.id: 'client-1'
  enable.auto.commit: True
  session.timeout.ms: 6000,
  default.topic.config: 
        auto.offset.reset: 'smallest'

kafka.controller.topics:
        - Market-Data
        - Config-Update
        - Bot-Admin

