kafka:
  bootstrap.servers: 'ec2-3-220-121-33.compute-1.amazonaws.com:9096,ec2-3-208-232-40.compute-1.amazonaws.com:9096,ec2-100-24-239-47.compute-1.amazonaws.com:9096,ec2-35-168-34-44.compute-1.amazonaws.com:9096,ec2-100-25-107-37.compute-1.amazonaws.com:9096,ec2-3-234-75-100.compute-1.amazonaws.com:9096,ec2-3-227-129-191.compute-1.amazonaws.com:9096,ec2-3-231-110-127.compute-1.amazonaws.com:9096'
  group.id: 'mygroup'
  client.id: 'client-1'
  enable.auto.commit: True
  session.timeout.ms: 6000
  security.protocol: 'SSL'
  default.topic.config: 
        auto.offset.reset: 'smallest'

kafka.controller.topics:
        - Market-Data
        - Config-Update
        - Bot-Admin

